SDL2_DIR = $(NXDK_DIR)/lib/sdl/SDL2

# Based on Makefile.minimal (some backends adapted for Xbox)
SDL2_SRCS := \
	$(wildcard $(SDL2_DIR)/src/*.c) \
	$(wildcard $(SDL2_DIR)/src/audio/*.c) \
	$(wildcard $(SDL2_DIR)/src/audio/xbox/*.c) \
	$(wildcard $(SDL2_DIR)/src/cpuinfo/*.c) \
	$(wildcard $(SDL2_DIR)/src/events/*.c) \
	$(wildcard $(SDL2_DIR)/src/file/*.c) \
	$(wildcard $(SDL2_DIR)/src/haptic/*.c) \
	$(wildcard $(SDL2_DIR)/src/haptic/dummy/*.c) \
	$(wildcard $(SDL2_DIR)/src/joystick/*.c) \
	$(wildcard $(SDL2_DIR)/src/joystick/xbox/*.c) \
	$(wildcard $(SDL2_DIR)/src/loadso/dummy/*.c) \
	$(wildcard $(SDL2_DIR)/src/power/*.c) \
	$(wildcard $(SDL2_DIR)/src/filesystem/dummy/*.c) \
	$(wildcard $(SDL2_DIR)/src/render/*.c) \
	$(wildcard $(SDL2_DIR)/src/render/software/*.c) \
	$(wildcard $(SDL2_DIR)/src/sensor/*.c) \
	$(wildcard $(SDL2_DIR)/src/sensor/dummy/*.c) \
	$(wildcard $(SDL2_DIR)/src/stdlib/*.c) \
	$(wildcard $(SDL2_DIR)/src/thread/*.c) \
	$(wildcard $(SDL2_DIR)/src/thread/windows/*.c) \
	$(wildcard $(SDL2_DIR)/src/timer/*.c) \
	$(wildcard $(SDL2_DIR)/src/timer/windows/*.c) \
	$(wildcard $(SDL2_DIR)/src/video/*.c) \
	$(wildcard $(SDL2_DIR)/src/video/xbox/*.c) \
	$(wildcard $(SDL2_DIR)/src/video/yuv2rgb/*.c)

# Additions for Xbox
SDL2_SRCS += \
	$(wildcard $(SDL2_DIR)/src/libm/*.c) \
	$(wildcard $(SDL2_DIR)/src/atomic/*.c)

NXDK_CFLAGS += -I$(SDL2_DIR)/include \
               -DXBOX

NXDK_CXXFLAGS += -I$(SDL2_DIR)/include \
                 -DXBOX

SDL2_OBJS = $(addsuffix .obj, $(basename $(SDL2_SRCS)))

$(NXDK_DIR)/lib/libSDL2.lib: $(SDL2_OBJS)

main.exe: $(NXDK_DIR)/lib/libSDL2.lib

CLEANRULES += clean-sdl2

.PHONY: clean-sdl2
clean-sdl2:
	$(VE)rm -f $(SDL2_OBJS) $(NXDK_DIR)/lib/libSDL2.lib
